- q: 'try tonumber catch ("__ERROR__")'
  in: foo
  out:
  - __ERROR__
